import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1781984201572 implements MigrationInterface {
    name = 'InitialMigration1781984201572'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`stations\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`address\` varchar(255) NOT NULL, \`latitude\` decimal(10,6) NOT NULL, \`longitude\` decimal(10,6) NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`status\` enum ('active', 'inactive', 'closed') NOT NULL DEFAULT 'active', \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`price\` decimal(10,2) NOT NULL, \`stock\` int NOT NULL DEFAULT '0', \`weight\` int NULL, \`size\` varchar(255) NULL, \`imageUrl\` varchar(255) NULL, \`isAvailable\` tinyint NOT NULL DEFAULT 1, \`type\` enum ('cylinder', 'accessory', 'service') NULL, \`stationId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` varchar(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`productId\` varchar(255) NULL, \`quantity\` int NOT NULL, \`price\` decimal(10,2) NOT NULL, \`subtotal\` decimal(10,2) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`deliveries\` (\`id\` varchar(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`driverId\` varchar(255) NOT NULL, \`driverName\` varchar(255) NULL, \`driverPhone\` varchar(255) NULL, \`vehicleNumber\` varchar(255) NULL, \`currentLocation\` json NULL, \`estimatedArrival\` datetime NULL, \`status\` enum ('assigned', 'accepted', 'picked_up', 'in_transit', 'nearby', 'arrived', 'delivered', 'completed', 'cancelled') NOT NULL DEFAULT 'assigned', \`route\` json NULL, \`pickupPhoto\` varchar(255) NULL, \`deliveryPhoto\` varchar(255) NULL, \`customerSignature\` varchar(255) NULL, \`deliveryNotes\` varchar(255) NULL, \`rating\` int NULL, \`review\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`totalAmount\` decimal(10,2) NOT NULL, \`status\` enum ('pending', 'confirmed', 'pending_assignment', 'driver_assigned', 'picked_up', 'in_transit', 'nearby', 'delivered', 'completed', 'cancelled', 'failed', 'refunded') NOT NULL DEFAULT 'pending', \`deliveryAddress\` varchar(255) NOT NULL, \`deliveryCity\` varchar(255) NULL, \`deliveryLatitude\` decimal(10,6) NULL, \`deliveryLongitude\` decimal(10,6) NULL, \`paymentMethod\` enum ('mtn', 'airtel', 'visa', 'wallet', 'cash') NULL, \`paymentStatus\` enum ('pending', 'completed', 'failed', 'refunded') NOT NULL DEFAULT 'pending', \`orderType\` enum ('quick', 'swap', 'buy_new', 'find_agent') NULL, \`trackingId\` varchar(255) NULL, \`notes\` varchar(255) NULL, \`stationId\` varchar(255) NULL, \`driverId\` varchar(255) NULL, \`estimatedDeliveryTime\` datetime NULL, \`actualDeliveryTime\` datetime NULL, \`cancellationReason\` varchar(255) NULL, \`cancelledAt\` datetime NULL, \`cancelledBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transactions\` (\`id\` varchar(36) NOT NULL, \`walletId\` varchar(255) NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`type\` enum ('credit', 'debit') NOT NULL, \`purpose\` enum ('top_up', 'order_payment', 'refund', 'withdrawal', 'bonus', 'adjustment') NOT NULL, \`orderId\` varchar(255) NULL, \`description\` varchar(255) NULL, \`status\` enum ('pending', 'completed', 'failed', 'reversed') NOT NULL DEFAULT 'completed', \`externalReference\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_e744417ceb0b530285c08f3865\` (\`createdAt\`), INDEX \`IDX_a88f466d39796d3081cf96e1b6\` (\`walletId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`wallets\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`balance\` decimal(10,2) NOT NULL DEFAULT '0.00', \`totalCredited\` decimal(10,2) NOT NULL DEFAULT '0.00', \`totalDebited\` decimal(10,2) NOT NULL DEFAULT '0.00', \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2ecdb33f23e9a6fc392025c0b9\` (\`userId\`), UNIQUE INDEX \`REL_2ecdb33f23e9a6fc392025c0b9\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`avatar\` varchar(255) NULL, \`address\` varchar(255) NULL, \`city\` varchar(255) NULL, \`state\` varchar(255) NULL, \`zipCode\` varchar(255) NULL, \`role\` enum ('customer', 'admin', 'agent', 'driver') NOT NULL DEFAULT 'customer', \`isActive\` tinyint NOT NULL DEFAULT 1, \`isEmailVerified\` tinyint NOT NULL DEFAULT 0, \`isPhoneVerified\` tinyint NOT NULL DEFAULT 0, \`stationId\` varchar(255) NULL, \`driverStatus\` enum ('online', 'offline', 'busy', 'on_break') NOT NULL DEFAULT 'offline', \`currentLatitude\` decimal(10,6) NULL, \`currentLongitude\` decimal(10,6) NULL, \`lastLocationUpdate\` datetime NULL, \`lastAssignedAt\` datetime NULL, \`vehicleNumber\` varchar(255) NULL, \`vehicleType\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_22c8e640d9c51a9e77e0733f134\` FOREIGN KEY (\`stationId\`) REFERENCES \`stations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_cdb99c05982d5191ac8465ac010\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deliveries\` ADD CONSTRAINT \`FK_f7433e3639e213f901e22cf8640\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_6229b6b048e99c564fd78497d84\` FOREIGN KEY (\`stationId\`) REFERENCES \`stations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_18dc786cf29d6ef99980ba6ae63\` FOREIGN KEY (\`driverId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_a88f466d39796d3081cf96e1b66\` FOREIGN KEY (\`walletId\`) REFERENCES \`wallets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wallets\` ADD CONSTRAINT \`FK_2ecdb33f23e9a6fc392025c0b97\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_94754bc4f5522eee5c245371906\` FOREIGN KEY (\`stationId\`) REFERENCES \`stations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_94754bc4f5522eee5c245371906\``);
        await queryRunner.query(`ALTER TABLE \`wallets\` DROP FOREIGN KEY \`FK_2ecdb33f23e9a6fc392025c0b97\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_a88f466d39796d3081cf96e1b66\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_18dc786cf29d6ef99980ba6ae63\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_6229b6b048e99c564fd78497d84\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`deliveries\` DROP FOREIGN KEY \`FK_f7433e3639e213f901e22cf8640\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_cdb99c05982d5191ac8465ac010\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_22c8e640d9c51a9e77e0733f134\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_2ecdb33f23e9a6fc392025c0b9\` ON \`wallets\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ecdb33f23e9a6fc392025c0b9\` ON \`wallets\``);
        await queryRunner.query(`DROP TABLE \`wallets\``);
        await queryRunner.query(`DROP INDEX \`IDX_a88f466d39796d3081cf96e1b6\` ON \`transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_e744417ceb0b530285c08f3865\` ON \`transactions\``);
        await queryRunner.query(`DROP TABLE \`transactions\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`deliveries\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP TABLE \`stations\``);
    }

}
